version: '3.8'

services:
  zamra-backend-blue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zamra-backend-blue
    restart: always
    ports:
      - "5000:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production

  zamra-backend-green:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zamra-backend-green
    restart: always
    ports:
      - "5001:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production