name: Zamra Backend CI/CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy-backend:
    name: Deploy Backend to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          timeout: 30m
          command_timeout: 30m
          pty: true
          debug: true
          script: |
            set -e
            cd ~/zamra/Zamra-backend
            git fetch origin
            git reset --hard origin/master
            ./scripts/deploy.sh

            echo "Deployment Finished Successfully"